#!/usr/bin/env ruby

if ARGV[0].nil? || ARGV[1].nil?
  puts "Usage:  pairs PATH_TO_COHORT_LIST GROUP_SIZE"
  exit 1
end

developers = File.readlines(ARGV[0], chomp: true)

developers.shuffle.each_slice(ARGV[1].to_i) do |group|
  puts group.join(", ")
end
