#!/usr/bin/env ruby

require 'json'

def usage
  puts "Usage:  mastery_quizzes_progress PATH_TO_COHORT_JSON PATH_TO_CHALLENGE_ATTEMPTS_JSON"
  exit 1
end

def read_json(path)
  raw_data = File.read(path)
  JSON.parse(raw_data)
end

def filter_challenge_attempts(attempts, github_usernames)
  attempts.select do |attempt|
    challenge = attempt.fetch("challenge")
    github_username = attempt.fetch("student").fetch("github_username")

    challenge == "mastery-quizzes" && github_usernames.include?(github_username)
  end
end

def print_summary(cohort, challenge_attempts)
  puts "Summary:"
  puts "#{cohort.length} in cohort"
  puts "#{challenge_attempts.length} total challenge attempts"
end

def latest_attempts(cohort, challenge_attempts)
  cohort.each_with_object(Hash.new({challenge_number: 0, marks: 0})) do |student, progress|
    name = student.fetch("name")
    github_username = student.fetch("github_username")

    students_challenge_attempts = challenge_attempts.select do |attempt|
      github_username == attempt.fetch("student").fetch("github_username")
    end

    students_challenge_attempts.each do |attempt|
      challenge_number = attempt.fetch("challenge_number")
      marks = attempt.fetch("marks")

      if progress[name].fetch(:challenge_number) < challenge_number
        progress[name] = {
          challenge_number: challenge_number,
          marks: marks
        }
      end
    end
  end
end

def print_progress(progress)
  puts "Progress through Mastery Quizzes:"
  progress.each do |name, latest_attempt|
    marks = latest_attempt.fetch(:marks)
    challenge_status = (marks == 100) ? "complete" : "in progress"
    puts "#{name}\t#{latest_attempt[:challenge_number]}\t#{challenge_status}"
  end
end

usage if ARGV[0].nil? || ARGV[1].nil?

cohort = read_json(ARGV[0])
unfiltered_challenge_attempts = read_json(ARGV[1])

github_usernames = cohort.map { |c| c.fetch("github_username") }

challenge_attempts = filter_challenge_attempts(unfiltered_challenge_attempts, github_usernames)

print_summary(cohort, challenge_attempts)

progress = latest_attempts(cohort, challenge_attempts)

puts ""
print_progress(progress)
